# Generated by Django 4.2 on 2024-02-23 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_answer_question_remove_answer_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('sub_title', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('price', models.FloatField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('meeting_link', models.CharField(blank=True, max_length=150)),
                ('speakers', models.CharField(max_length=100)),
                ('image', models.FileField(null=True, upload_to='events/%Y:%m:%d')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('event_date', models.DateTimeField(max_length=100)),
                ('add_to_homepage', models.BooleanField(default=False)),
                ('regular_event', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('video_link', models.CharField(blank=True, max_length=150)),
                ('file', models.FileField(null=True, upload_to='blogs/%Y:%m:%d')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
