# Generated by Django 4.2 on 2024-02-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_event_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='file',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='meeting_link',
            new_name='eventbrite_link',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='video_link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='add_to_homepage',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='regular_event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='speakers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.CharField(default='DevOps Blogs', max_length=50),
        ),
    ]
